class MyClass {
    int foo2(int value1, int value2, int value3, int value4, int value5) { // Noncompliant
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        unction();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        unction();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        unction();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        unction();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        function();
        return 0;
    }

    int foo3(int value) {
        return 0;
    }
}